%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: optimal_PnP_quat
problem_print_out_name: Optimal PnP with quaternion parameterization

#> Reference: Nakano, Gaku. "Globally Optimal DLS Method for PnP Problem with Cayley parameterization." 
#  In BMVC, vol. 78, pp. 1-78. 2015.

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 30
GPUHC_Max_Correction_Steps: 200
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 2

#> Problem spec
Num_Of_Vars: 4
Num_Of_Params: 81
Num_Of_Tracks: 80
dHdx_Max_Terms: 20
dHdx_Max_Parts: 5
dHdt_Max_Terms: 35
dHdt_Max_Parts: 6
Max_Order_Of_T: 1
Num_Of_Coeffs_From_Params: 105

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
