%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: uncalibrated_trifocal_rel_pos_CY
problem_print_out_name: Uncalibrated Trifocal Relative Pose Problem (Chiang-Heng & Yaqing Version)

#> Reference: This is from a formulation of our GPU-HC journal version. Will be updated.

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 100
GPUHC_Max_Correction_Steps: 3
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 2

#> Problem spec
Num_Of_Vars: 12
Num_Of_Params: 24
Num_Of_Tracks: 668
dHdx_Max_Terms: 6
dHdx_Max_Parts: 4
dHdt_Max_Terms: 12
dHdt_Max_Parts: 5
Max_Order_Of_T: 2
Num_Of_Coeffs_From_Params: 30

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
