%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: 3view_triangulation
problem_print_out_name: 3-View Triangulation

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 50
GPUHC_Max_Correction_Steps: 200
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 5

#> Problem spec
Num_Of_Vars: 8
Num_Of_Params: 24
Num_Of_Tracks: 31
dHdx_Max_Terms: 3
dHdx_Max_Parts: 3
dHdt_Max_Terms: 9
dHdt_Max_Parts: 4
Max_Order_Of_T: 1
Num_Of_Coeffs_From_Params: 24

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
