%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: uncalibrated_trifocal_rel_pos_CH
problem_print_out_name: Uncalibrated Trifocal Relative Pose Problem (Chiang-Heng & Hongyi Version)

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 50
GPUHC_Max_Correction_Steps: 10
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 2

#> Problem spec
Num_Of_Vars: 18
Num_Of_Params: 24
Num_Of_Tracks: 5344
dHdx_Max_Terms: 12
dHdx_Max_Parts: 6
dHdt_Max_Terms: 14
dHdt_Max_Parts: 7
Max_Order_Of_T: 2
Num_Of_Coeffs_From_Params: 88

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
