%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: 5pt_rel_pos_alg_form_quat
problem_print_out_name: 5-Point Relative Pose Problem (Algebraic Form with Quaternion)

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 42
GPUHC_Max_Correction_Steps: 300
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 2

#> Problem spec
Num_Of_Vars: 6
Num_Of_Params: 20
Num_Of_Tracks: 40
Num_Of_Coeffs_From_Params: 75
dHdx_Max_Terms: 12
dHdx_Max_Parts: 4
dHdt_Max_Terms: 30
dHdt_Max_Parts: 5
Max_Order_Of_T: 2

RANSAC_Dataset: None
