%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: distorted_2view_triangulation
problem_print_out_name: 2-view triangulation with distortion

#> Reference: Kukelova, Zuzana, and Viktor Larsson. "Radial distortion triangulation." 
#  In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition, 
#  pp. 9681-9689. 2019.

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 100
GPUHC_Max_Correction_Steps: 250
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 2

#> Problem spec
Num_Of_Vars: 5
Num_Of_Params: 15
Num_Of_Tracks: 28
dHdx_Max_Terms: 10
dHdx_Max_Parts: 5
dHdt_Max_Terms: 25
dHdt_Max_Parts: 6
Max_Order_Of_T: 3
Num_Of_Coeffs_From_Params: 24

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
