%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: 3pt_rel_pos_homog
problem_print_out_name: Homography Constrained 3-Point Relative Pose Estimation

#> Reference: O. Saurer, P. Vasseur, C. Demonceaux, and F. Fraundorfer. A homography 
#  formulation to the 3pt plus a common direction relative pose problem. In Asian Conference  
#  on Computer Vision, pages 288–301. Springer, 2014

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 50
GPUHC_Max_Correction_Steps: 10
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 3

#> Problem spec
Num_Of_Vars: 8
Num_Of_Params: 18
Num_Of_Tracks: 8
dHdx_Max_Terms: 6
dHdx_Max_Parts: 4
dHdt_Max_Terms: 9
dHdt_Max_Parts: 5
Max_Order_Of_T: 2
Num_Of_Coeffs_From_Params: 27

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
