%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: 4view_triangulation
problem_print_out_name: 4-View Triangulation

#> Reference: Chien, Chiang-Heng, Hongyi Fan, Ahmad Abdelfattah, Elias Tsigaridas, Stanimire Tomov, and Benjamin Kimia. 
#  "GPU-based homotopy continuation for minimal problems in computer vision." In Proceedings of the IEEE/CVF Conference 
#  on Computer Vision and Pattern Recognition, pp. 15765-15776. 2022.

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 80
GPUHC_Max_Correction_Steps: 250
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 5

#> Problem spec
Num_Of_Vars: 11
Num_Of_Params: 35
Num_Of_Tracks: 142
dHdx_Max_Terms: 3
dHdx_Max_Parts: 3
dHdt_Max_Terms: 9
dHdt_Max_Parts: 4
Max_Order_Of_T: 1
Num_Of_Coeffs_From_Params: 35

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
